### ISSUE TITLE
Quill formats feature blocking the LanguageTool

### ISSUE THREAD

**Issue by sream** [vantezzen/quill-languagetool#3]
Setting the Quill formats feature breaks the LanguageTool. Is there any workaround for this problem?

@vantezzen

**Comment by vantezzen** [comment]
I have not explicitly worked with the formats feature, only used the default config. Feel free to comment if you find a workaround.

**Comment by sream** [comment]
I've figured it out. You've named the blot _ltmatch_ inside the src/SuggestionBlot.ts. Initially I've tried _quill-lt-match_ and _lt-match_ because that's what I've expected based on the tags produced in the DOM. Maybe you can add that to the readme. Once passed under that named to formats it works as intended.
